version: '3.8'

services:
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  python:
    build: ./python
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - postgresql

  react:
    build: ./react
    restart: always
    ports:
      - "3000:3000"

  keycloak:
    image: jboss/keycloak:latest
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: POSTGRES
      DB_ADDR: postgresql
      DB_PORT: 5432
      DB_DATABASE: your_database_name
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
    ports:
      - "8080:8080"

volumes:
  db_data:
